### ISSUE TITLE
edit adapters.py

### ISSUE THREAD

**Issue by thierryjanssens** [ejongepier/NanoClass#1]
Hi,

where can the adapters.py file of porechop be edited?
Since the env is created on the fly by snakemake it is unclear where I can edit this file.

kind regards,

Thierry

**Comment by ejongepier** [comment]
Hi Thierry,

If you did not yet run NanoClass and thus did not create the environments, first run:
`snakemake --use-conda --conda-create-envs-only`

Then, you can find the adapters.py with smth like:
`find .snakemake/conda/ -name adapters.py`

For me it is here `.snakemake/conda/61297cd9/lib/python3.9/site-packages/porechop/adapters.py`
but your conda environment is probably not labeled 61297cd9. 

Hope that helps.

Best,
Evelien
