### ISSUE TITLE
Error in generating report

### ISSUE THREAD

**Issue by thierryjanssens** [ejongepier/NanoClass#3]
Hi,

after a flawless run of a metabarcoding dataset on the UNITE db I wanted to generate the report.

snakemake --report report/NanoClass.zip

Building DAG of jobs...
Creating report...
Adding dummymost1.filtered.pdf (0.091 MB).
Adding dummymost2.filtered.pdf (0.094 MB).
Adding dummymost1adapted.filtered.pdf (0.076 MB).
Adding dummymost2adapted.filtered.pdf (0.072 MB).
Adding aabund-Phylum-by-sample.pdf (0.0056 MB).
Adding rabund-Phylum-by-sample.pdf (0.0057 MB).
Adding aabund-Class-by-sample.pdf (0.006 MB).
Adding rabund-Class-by-sample.pdf (0.006 MB).
Adding aabund-Order-by-sample.pdf (0.0062 MB).
Adding rabund-Order-by-sample.pdf (0.0063 MB).
Adding aabund-Family-by-sample.pdf (0.0066 MB).
Adding rabund-Family-by-sample.pdf (0.0065 MB).
Adding aabund-Genus-by-sample.pdf (0.006 MB).
Adding rabund-Genus-by-sample.pdf (0.0062 MB).
Adding runtime-by-sample.pdf (0.0051 MB).
Adding runtime_log-by-sample.pdf (0.005 MB).
WorkflowError:
Error loading caption file of output marked for report.
WorkflowError:
    Failed to open source file /home/minion/git/NanoClass/rules/../report/fig-nanofilt.rst
    FileNotFoundError: [Errno 2] No such file or directory: '/home/minion/git/NanoClass/rules/../report/fig-nanofilt.rst'

Kind regards,

Thierry

**Comment by ejongepier** [comment]
Hi Thierry,

I cannot recreate your error. Might have something to do with different version of snakemake as the snakemake reporting function has changed a bit in recent versions.

Could you:

1. Check whether the file report/fig-nanofilt.rst exists.
2. If it does, add some line to this empty file, e.g. "Nanofilt results"
3. Run `snakemake --report report/NanoClass.zip` again.

If this does not help, pls let me know what snakemake version you are using.

Best,
Evelien

**Comment by thierryjanssens** [comment]
Hi Evelien,

no folder report/ was created unfortunately.

$ snakemake --version
6.8.0              

Kind regards,

Thierry

**Comment by ejongepier** [comment]
Hi Thierry,

Looks like you accidentally deleted it because there is report directory in the repo: https://github.com/ejongepier/NanoClass/tree/master/report.

Best,
Evelien
