### ISSUE TITLE
Missing input files for rule common_plot_tax

### ISSUE THREAD

**Issue by thierryjanssens** [ejongepier/NanoClass#4]
Hello Evlien,

with a fresh install from github, a new samples.csv file and the UNITE db in db/common/ I get the following error just after startup

Building DAG of jobs...
MissingInputException in line 33 of /media/minion/Data/Analyses/FlevoRUN/NanoClass/rules/common.smk:
Missing input files for rule common_plot_tax:
classifications/FlevoRUN3/blastn/PLA_RON_t=1_A.blastn.taxmat

It seems to lack a link to the taxmat files.

kind regards,

Thierry

**Comment by ejongepier** [comment]
Hi Thierry,

SampleIDs should only contain alphanumeric characters (see [README](https://github.com/ejongepier/NanoClass#readme) and [Documentation](https://ejongepier.github.io/NanoClass/))

Could you change your sampleID in the samples.csv from PLA_RON_t=1_A to e.g. PlaRonT1 and try again?

Best,
Evelien

**Comment by thierryjanssens** [comment]
🙄 oh OK.

Thanks

**Comment by thierryjanssens** [comment]
It works now.
