### ISSUE TITLE
Total analysis time

### ISSUE THREAD

**Issue by thierryjanssens** [ejongepier/NanoClass#5]
Hi,

since last week I have a Nanoclass 16S analysis running (approximately 3 Mreads on 4 samples) on 56 cores. I have selected the blastn method.
The last update of the snakemake output/log mentioned 48% since last Wednesday.

I am doubting this is the way Nanoclass was meant to be used, Is there something that I overlooked?

kind regards and thanks in advance,

Thierry

**Comment by ejongepier** [comment]
Hi Thierry,

That is a pretty massive dataset.
I'd recommend using minimap, which yields very similar classifications as blast and is orders of magnitude faster.

If you insist on blast, select megablast. It works just as well in my experience as blastn and is faster. In that case, still be prepared for a long run...

By default blastn (or megablast) runs 10 parallel processes, so 4 samples x 10 threads is 40 which means 16 of your threads remain idle for most of your run. Perhaps change to 14 threads in the config.yaml. Same applies for minimap, which takes 16 threads by default. Changing it to 14 allows you to analyze all 4 samples in parallel.

Best,
Evelien
